name: on-schedule
run-name: on schedule

on:
  schedule:
    # every Monday at midnight UTC
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-citations:
    uses: ./.github/workflows/update-citations.yaml
    with:
      open-pr: true

  update-network:
    needs: update-citations
    uses: ./.github/workflows/update-network.yaml

  update-gallery:
    needs: update-network
    uses: ./.github/workflows/update-gallery.yaml

  build-site:
    needs: [update-citations, update-network, update-gallery]
    uses: ./.github/workflows/build-site.yaml
