name: update-gallery
run-name: update gallery metadata

on:
  # run when called from another workflow
  workflow_call:
    outputs:
      changed:
        value: ${{ jobs.update-gallery.outputs.changed }}

  # run if user manually requests it
  workflow_dispatch:

  # run when images are added/changed in the lab directory
  push:
    paths:
      - 'images/lab/**'
      - '_scripts/generate_gallery_metadata.py'

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: true

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python packages for gallery generation
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade Pillow

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Generate gallery metadata
        if: github.event.action != 'closed'
        run: python _scripts/gallery.py
        timeout-minutes: 3

      - name: Check if gallery.json changed
        if: github.event.action != 'closed'
        id: changed
        uses: tj-actions/verify-changed-files@v18
        with:
          files: |
            images/lab/gallery.json

      - name: Commit updated gallery.json to branch
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update gallery metadata"
          file_pattern: "images/lab/gallery.json"
          pull_before_push: true        # ðŸ‘ˆ key addition to handle concurrent pushes safely

    outputs:
      changed: ${{ steps.changed.outputs.files_changed || false }}
